### ISSUE TITLE
Allow code block with opening and closing tags

### ISSUE THREAD

**Issue by sarim** [Rabrennie/jupyter-php-kernel#4]
Code block with `<?php` gives an error `PHP Parse error: Syntax error, unexpected '<' on line 1`
If there any way to make the enable accept the start tag?

I'm using jupyter in vscode. Without <?php tag, vscode's php syntax highlighting and intelephense doesn't enable.

Screenshot for clarify.

![image](https://user-images.githubusercontent.com/1235888/152716902-b2fa933a-1bf6-4612-a5e7-28e196a3e0a2.png)

Is there any easy way to (maybe add a flag somewhere) to make php-kernel accept the start tag?

**Comment by Rabrennie** [comment]
Hi @sarim, I've pushed a change that should allow running cells with php tags

You can update the kernel to the latest version by running 
```bash
composer global update rabrennie/jupyter-php-kernel
```
